BOARD_WIDTH = BOARD_HEIGHT = 512
MOVE_LOG_PANEL_WIDTH = BOARD_WIDTH//2
MOVE_LOG_PANEL_HEIGHT = BOARD_HEIGHT
DIMS = 8
SQ_SIZE = BOARD_HEIGHT // DIMS
MAX_FPS = 15
FOUR_WAY_DIRS = [(-1, 0), (0, 1), (1, 0), (0, -1)]  # UP, RIGHT, DOWN, LEFT
DIAGONAL_DIRS = [(-1, -1), (-1, 1), (1, 1), (1, -1)]  # TOP_LEFT, TOP_RIGHT, BOTTOM_RIGHT, BOTTOM_LEFT
KNIGHT_DIRS = [(-1, -2), (-2, -1), (-2, 1), (-1, 2), (1, -2), (2, -1), (2, 1), (1, 2)]
COLORS = ["white", "gray"]
